@startuml
allowmixing

package "core" {
    interface Sensor {
        +get_reading(): int
    }
    interface BrightnessModel {
        +map(reading: int): int
    }
    interface Display {
        +set_brightness(brightness: int)
    }
}

class ColorHug {
        get_reading(): int
}
class DDCControl {
        set_brightness(brightness: int)
        device: int
}
class ProportionalBrightnessModel {
        map(reading: int): int
}

Sensor <|-- ColorHug
BrightnessModel <|-- ProportionalBrightnessModel
Display <|-- DDCControl

class Measurements {
add_measurement(reading: int, brightness: int): None
get_measurements(): pd.DataFrame
path: pathlib.Path
df: pd.DataFrame
}

usecase Web
usecase CLI

Web --> Sensor
Web --> Display
Web --> Measurements

CLI --> Sensor
CLI --> Display
CLI --> BrightnessModel
@enduml