#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2016 Martin Ueding <martin-ueding.de>

import argparse
import os
import datetime
import re
import tempfile
import subprocess


def main():
    options = _parse_args()

    command = ['ddccontrol',
               '-r', '0x10',
               'dev:/dev/i2c-' + options.device]

    with tempfile.TemporaryFile() as buf:
        subprocess.call(command, stdout=buf)
        buf.seek(0)
        output = buf.read().decode()

    m = re.search(r'Control 0x10: \+/(\d+)/100 C \[Brightness\]', output)
    if m:
        brightness = m.group(1)
        print(brightness)

        with open(os.path.expanduser('~/.local/ddc-brightness.txt'), 'a') as f:
            now = datetime.datetime.now()
            f.write('{} {}\n'.format(now.isoformat(), brightness))

def _parse_args():
    '''
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    '''
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('--device', default='7')
    options = parser.parse_args()

    return options


if __name__ == '__main__':
    main()
